package com.ingramcontent.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FeedStatusConfigRule implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer maxRetires;

	public FeedStatusConfigRule() {
	}

	public java.lang.Integer getMaxRetires() {
		return this.maxRetires;
	}

	public void setMaxRetires(java.lang.Integer maxRetires) {
		this.maxRetires = maxRetires;
	}

	public FeedStatusConfigRule(java.lang.Integer maxRetires) {
		this.maxRetires = maxRetires;
	}

}