package com.ingramcontent.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WalmartProductConfig implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public WalmartProductConfig() {
    }




}